#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-only
/**
 * SM4-GCM KAT verifier
 * =====================
 * Runs the 30 vectors in ./sm4-gcm-KAT.json against src/sm4-browser.js and exits
 * non-zero on any ciphertext OR tag mismatch.
 *
 * Vectors: copied from fibemate/packages/sm4-ref/test/kat/sm4-gcm-KAT.json
 * (generated by packages/sm4-ref/python/sm4_ref.py). They are a
 * cross-implementation reference, not NIST/GM published vectors — they catch
 * divergence between the JS and the Python reference, which is the failure mode
 * we actually hit (a GHASH tag bug that the implementation's own self-test could
 * not see, because the self-test never exercised AAD/multi-block input).
 *
 * ⚠️ AAD MUST BE PASSED AS RAW BYTES (Uint8Array / Buffer).
 *    Passing a hex string makes encrypt() run it through TextEncoder, i.e. it
 *    authenticates the *ASCII of the hex text* instead of the bytes, and you get
 *    20/30 with the exact signature "ciphertext right, tag wrong". Ten of the 30
 *    vectors carry AAD, so that mistake silently looks like a GHASH bug.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// src/sm4-browser.js is a browser IIFE that assigns window.SM4GCM — shim a window.
global.window = global;
global.self = global;
if (!global.crypto) global.crypto = crypto.webcrypto;
require(path.resolve(__dirname, '../../../src/sm4-browser.js'));

const G = global.SM4GCM;
if (!G || typeof G.encrypt !== 'function') { console.error('[FAIL] window.SM4GCM not exposed by src/sm4-browser.js'); process.exit(1); }

const vectors = Object.values(JSON.parse(fs.readFileSync(path.join(__dirname, 'sm4-gcm-KAT.json'), 'utf8')));
let pass = 0;
const failures = [];

for (const v of vectors) {
  const opts = { iv: v.iv };
  if (v.aad) opts.aad = new Uint8Array(Buffer.from(v.aad, 'hex')); // ← raw bytes, never the hex string
  let r;
  try {
    r = G.encrypt(new Uint8Array(Buffer.from(v.pt, 'hex')), v.key, opts);
  } catch (e) { failures.push({ count: v.count, error: e.message }); continue; }
  const ctOk = String(r.ciphertext).toLowerCase() === v.ct.toLowerCase();
  const tagOk = String(r.authTag).toLowerCase() === v.tag.toLowerCase();
  if (ctOk && tagOk) pass++;
  else failures.push({ count: v.count, ctOk, tagOk, gotTag: String(r.authTag), wantTag: v.tag });
}

const withAad = vectors.filter((v) => v.aad).length;
console.log(`[SM4-GCM KAT] ${pass}/${vectors.length} passed (${withAad} vectors carry AAD)`);
if (failures.length) {
  console.error('[FAIL] mismatches:');
  for (const f of failures.slice(0, 10)) console.error('  ' + JSON.stringify(f));
  console.error('Hint: if ciphertext is correct but the tag is wrong on exactly the AAD vectors,' +
    ' check that AAD was passed as raw bytes.');
  process.exit(1);
}
console.log('[OK] every ciphertext and auth tag matches the reference vectors');
